MiProyecto/MiProyecto/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import index


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('home.urls', 'home'))),
    path('voluntariado/', include(('voluntariado.urls',"voluntariado"))),
    path('producto/',include(('producto.urls','producto')))
]

MiProyecto/apps/cliente/urls.py
from django.urls import path
from .views import index, crear_clientes_predeterminados, prueba_busqueda, crear_cliente 

app_name='cliente'

urlpatterns = [
    path('', index, name='index'),
    path('crear-clientes/',crear_clientes_predeterminados ,name='crear-clientes'),
    path('prueba-busqueda/', prueba_busqueda, name='prueba-busqueda'),
    path('crear/',crear_cliente,name='crear')
]

MiProyecto/apps/home/urls.py
from django.urls import path
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    path('',views.index, name='index' ),
    #staticfiles_urlpatterns()
]
urlpatterns += staticfiles_urlpatterns()

MiProyecto/apps/producto/urls.py
from django.urls import path, include
from . import views


urlpatterns = [
    path('',views.index, name='index' ),
    path('producto_categoria_list/', views.ProductoCategoriaList.as_view(), name= "producto_categoria_list"),
    path('producto_categoria_pedido/', views.producto_categoria_pedido, name='producto_categoria_pedido'),
    path('producto_categoria_delete/<int:id>', views.producto_categoria_delete, name='producto_categoria_delete'),
    path('producto_categoria_update/<int:id>', views.producto_categoria_update, name='producto_categoria_update'),
]
    

MiProyecto/apps/voluntariado/urls.py
from django.urls import path, include
from . import views


urlpatterns = [
    path('',views.index, name='index' ),
]
    

MiProyecto/apps/cliente/models.py
from django.db import models

class Pais(models.Model):
    nombre = models.CharField(max_length=50)
    def __str__(self):
        return self.nombre


class Cliente(models.Model):
    nombre = models.CharField(max_length=50)
    apellido = models.CharField(max_length=50)
    nacimiento = models.DateField(null=True)
    pais_origen_id = models.ForeignKey(Pais, on_delete=models.SET_NULL, null=True)
    def __str__(self):
        return self.nombre

MiProyecto/apps/home/models.py
from django.db import models

# Create your models here.

MiProyecto/apps/producto/models.py
from django.db import models

# Create your models here.
class ProductoCategoria(models.Model):
    nombre= models.CharField(max_length=100,unique=True)
    descripcion=models.CharField(max_length=250,null=True,blank=True )

    class Meta:
        verbose_name = 'Categoria de productos'
        verbose_name_plural='Categorias de productos'
    def __str__(self) :
        return self.nombre

MiProyecto/apps/voluntariado/models.py
from django.db import models

# Create your models here.

MiProyecto/apps/cliente/forms.py
from django import forms

from .models import Cliente


class ClienteForm(forms.ModelForm):
    class Meta:
        model = Cliente
        fields = ["nombre", "apellido", "nacimiento", "pais_origen_id"]

#class ClienteForm(forms.ModelForm):
 #   class Meta:
  #      model = Pais
   #     fields = '__all__'

MiProyecto/apps/producto/forms.py
from django import forms
from . import models

class ProductoCategoriaForm(forms.ModelForm):
    class Meta:
        model = models.ProductoCategoria
        fields = '__all__'

MiProyecto/MiProyecto/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

MiProyecto/apps/cliente/views.py
from django.shortcuts import render, redirect
from .models import Cliente, Pais

# Create your views here.
def index(request):
    clientes_registro= Cliente.objects.all()
    datos= {'clientes': clientes_registro}
    return render(request, 'cliente/index_cliente.html', datos)


def crear_clientes_predeterminados(request): 
    from datetime import date 
    #crear instancias de paises
    p1=Pais.objects.create(nombre="colombia")
    p2=Pais.objects.create(nombre='EStados Unidos')
    p3=Pais.objects.create(nombre='Argentina')

    #crear clientes
    Cliente.objects.create(nombre='Almendra',apellido="Ruisenor", nacimiento=date(2015,1,1),pais_origen_id=p1)
    Cliente.objects.create(nombre='Martina',apellido="Martinez", nacimiento=date(2008,7,3),pais_origen_id=None)
    Cliente.objects.create(nombre='Julian',apellido="Alvarez", nacimiento=date(2000,1,31),pais_origen_id=None)
    Cliente.objects.create(nombre='Aldana',apellido="Gonzalez", nacimiento=date(2004,7,4),pais_origen_id=p2)

    #return render(request, 'cliente/index_cliente.html')
    return redirect('cliente:index')

def prueba_busqueda(request):
    from datetime import date 
    contexto={}
    #busqueda por nombre que contenga "dana"
    clientes_nombre = Cliente.objects.filter(nombre__contains="dana")
    contexto['clientes_nombre']= clientes_nombre
    
    #busqueda por fecha de nacimiento mayor a 2000
    clientes_nacimiento = Cliente.objects.filter(nacimiento__gte=date(2000,1,1))   
    contexto['clientes_nacimiento']= clientes_nacimiento
    

    #busqueda por cliente que no tenga pais
    clientes_sin_pais = Cliente.objects.filter(pais_origen_id=None)
    contexto['clientes_sin_pais']= clientes_sin_pais
    
    return render(request, 'cliente/resultado_busqueda.html', contexto)

def crear_cliente(request):
    from .forms import ClienteForm 
    if request.method == 'POST':
        form= ClienteForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('cliente:index')
    else: #method==GET
        form= ClienteForm()
    return render(request, 'cliente/crear.html',{'form':form})

MiProyecto/apps/home/views.py
from django.shortcuts import render

# Create your views here.
def index (request):
    return render(request, 'home/index.html')

MiProyecto/apps/producto/views.py
from django.shortcuts import render, redirect
from . import models
from django.template import context
from . import forms

# Create your views here.
def index (request):
    return render(request, 'producto/index.html')

from django.views.generic import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView

class ProductoCategoriaList(ListView):
    model = models.ProductoCategoria
    template_name = 'producto/producto_categoria_list.html'
    context_object_name = 'categorias'


def producto_categoria_list(request):
    categorias=models.ProductoCategoria.objects.all()
    context={'categorias':categorias}
    return render(request, 'producto/producto_categoria_list.html', context)

def producto_categoria_pedido(request):
    if request.method =='POST':
      form = forms.ProductoCategoriaForm(request.POST)
      if form.is_valid():
          form.save()
          return redirect ('producto:index')
    else:
        form= forms.ProductoCategoriaForm()
    return render(request, 'producto/producto_categoria_pedido.html', {'form':form})

def producto_categoria_delete(request,id):
    categoria=models.ProductoCategoria.objects.get(id=id)
    if request.method=='POST':
        categoria.delete()
        return redirect('producto:index')
    return render(request, 'producto/producto_categoria_delete.html',{'categoria': categoria})

def producto_categoria_update(request,id):
    categoria=models.ProductoCategoria.objects.get(id=id)
    if request.method =='POST':
      form = forms.ProductoCategoriaForm(request.POST,instance=categoria)
      if form.is_valid():
          form.save()
          return redirect ('producto:index')
    else:
        form= forms.ProductoCategoriaForm(instance=categoria)
    return render(request, 'producto/producto_categoria_update.html', {'form':form})

MiProyecto/apps/voluntariado/views.py
from django.shortcuts import render

# Create your views here.
def index (request):
    return render(request, 'voluntariado/index.html')

MiProyecto/apps/cliente/templates/cliente/crear.html
{% extends 'base.html' %}
{% block TITULO %} Crear cliente {% endblock %}
    
{% block CONTENIDO %}
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p  }}
        <button type="submit"> Guardar </button>
    </form>
{% endblock CONTENIDO %}

MiProyecto/apps/cliente/templates/cliente/index_cliente.html
{% extends 'base.html' %}
{% block TITULO %}
    CLIENTES
{% endblock TITULO %}

{% block CONTENIDO %}
    

    {% for cliente in clientes %}
        <h2>{{cliente.nombre}}</h2>
        <p>{{cliente.apellido}}</p>
        <p>{{cliente.nacimiento}}</p>
    {% endfor %}
    <a href="{% url 'cliente:crear' %}">Crear clientes </a>
    <br>
    <a href="{% url 'cliente:crear-clientes' %}">Crear datos de clientes pre-establecidos</a>
    <br>
    <a href="{% url 'cliente:prueba-busqueda' %}">Prueba busqueda</a>
    <br>
    <a href="{% url 'index' %}">Ir al inicio</a>

{% endblock CONTENIDO %}  

MiProyecto/apps/cliente/templates/cliente/resultado_busqueda.html
{% extends 'base.html' %}

{% block TITULO %}
    RESULTADOS DE LA BUSQUEDA
{% endblock TITULO %}
{% block CONTENIDO %}
<h2>NOMBRE</h2>
{% for cliente in clientes_nombre  %}
    <p>{{ cliente | upper }}</p>
{% endfor %}
<h2>nacimiento</h2>
{% for cliente  in clientes_nacimiento  %}
        <p> {{cliente}}</p>
{% endfor %}

<h2>CLIENTE SIN PAIS</h2>
{% for cliente in clientes_sin_pais  %}
    <p> {{cliente}} </p>
{% endfor %}
    <a href="{% url 'index' %}">Ir al inicio</a>
{% endblock  %}

MiProyecto/apps/home/templates/home/base.html
{% load static %}

<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Punto de Encuentro</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'home/assets/favicon.ico' %}" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'home/css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
       
        {% include 'home/navbar.html' %}

        <!-- Page Content-->
        <div class="container px-4 px-lg-5">
            <!-- Heading Row-->
        {% block content %}
            
        {% endblock content %}
            
        {% include 'home/footer.html' %}

        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'home/js/scripts.js' %}"></script>
    </body>
</html>

MiProyecto/apps/home/templates/home/footer.html
<!-- Footer-->
<footer class="py-3 bg-dark">
    <div class="container px-4 px-lg-5"><p class="m-0 text-center text-white">Copyright &copy; Your Website 2023</p></div>
</footer>

MiProyecto/apps/home/templates/home/index.html
{% extends 'home/base.html' %}

{% block content %}
    <div class="row gx-4 gx-lg-5 align-items-center my-5">
                <div class="col-lg-7"><img class="img-fluid rounded mb-4 mb-lg-0" src="https://i.pinimg.com/564x/99/5c/f6/995cf65121193ee0fe9a6adc78f2f9d7.jpg" alt="..." /></div>
                <div class="col-lg-5">
                    <h1 class="font-weight-light" href="{% url 'home:index' %}">Punto de Encuentro</h1>
                    <p>¡Bienvenid@s a nuestro emprendimiento familiar! Este es un proyecto que nace del amor de hacer cosas con dedicación, paciencia, bsucando que cada pieza sea única con la hermosa calidad de siempre. Soy Pía, espero que disfrutes dela experiencia</p>
                    <a class="btn btn-primary" href="{% url 'producto:index' %}">Quiero ver los productos</a>
                </div>
            </div>
            <!-- Call to Action-->
            <div class="card text-white bg-secondary my-5 py-4 text-center">
                <div class="card-body"><p class="text-white m-0">El 15% de la ganancia de nuestros productos van destinados a la fabricacion de piezas para donar a diferentes asociaciones y voluntariados, acompañandolos en su tarea y ayudando a los que mas lo necesitan.</p></div>
            </div>
            <!-- Content Row-->
            <div class="row gx-4 gx-lg-5">
                <div class="col-md-4 mb-5">
                    <div class="card h-100">
                        <div class="card-body">
                            <h2 class="card-title">Card One</h2>
                            <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Rem magni quas ex numquam, maxime minus quam molestias corporis quod, ea minima accusamus.</p>
                        </div>
                        <div class="card-footer"><a class="btn btn-primary btn-sm" href="#!">More Info</a></div>
                    </div>
                </div>
                <div class="col-md-4 mb-5">
                    <div class="card h-100">
                        <div class="card-body">
                            <h2 class="card-title">Card Two</h2>
                            <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quod tenetur ex natus at dolorem enim! Nesciunt pariatur voluptatem sunt quam eaque, vel, non in id dolore voluptates quos eligendi labore.</p>
                        </div>
                        <div class="card-footer"><a class="btn btn-primary btn-sm" href="#!">More Info</a></div>
                    </div>
                </div>
                <div class="col-md-4 mb-5">
                    <div class="card h-100">
                        <div class="card-body">
                            <h2 class="card-title">Card Three</h2>
                            <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Rem magni quas ex numquam, maxime minus quam molestias corporis quod, ea minima accusamus.</p>
                        </div>
                        <div class="card-footer"><a class="btn btn-primary btn-sm" href="#!">More Info</a></div>
                    </div>
                </div>
            </div>
        </div>
{% endblock content %}<div class="row gx-4 gx-lg-5 align-items-center my-5">
                <div class="col-lg-7"><img class="img-fluid rounded mb-4 mb-lg-0" src="https://i.pinimg.com/564x/99/5c/f6/995cf65121193ee0fe9a6adc78f2f9d7.jpg" alt="..." /></div>
                <div class="col-lg-5">
                    <h1 class="font-weight-light">Punto de Encuentro</h1>
                    <p>This is a template that is great for small businesses. It doesn't have too much fancy flare to it, but it makes a great use of the standard Bootstrap core components. Feel free to use this template for any project you want!</p>
                    <a class="btn btn-primary" href="#!">Call to Action!</a>
                </div>
            </div>
            <!-- Call to Action-->
            <div class="card text-white bg-secondary my-5 py-4 text-center">
                <div class="card-body"><p class="text-white m-0">This call to action card is a great place to showcase some important information or display a clever tagline!</p></div>
            </div>
            <!-- Content Row-->
            <div class="row gx-4 gx-lg-5">
                <div class="col-md-4 mb-5">
                    <div class="card h-100">
                        <div class="card-body">
                            <h2 class="card-title">Card One</h2>
                            <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Rem magni quas ex numquam, maxime minus quam molestias corporis quod, ea minima accusamus.</p>
                        </div>
                        <div class="card-footer"><a class="btn btn-primary btn-sm" href="#!">More Info</a></div>
                    </div>
                </div>
                <div class="col-md-4 mb-5">
                    <div class="card h-100">
                        <div class="card-body">
                            <h2 class="card-title">Card Two</h2>
                            <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quod tenetur ex natus at dolorem enim! Nesciunt pariatur voluptatem sunt quam eaque, vel, non in id dolore voluptates quos eligendi labore.</p>
                        </div>
                        <div class="card-footer"><a class="btn btn-primary btn-sm" href="#!">More Info</a></div>
                    </div>
                </div>
                <div class="col-md-4 mb-5">
                    <div class="card h-100">
                        <div class="card-body">
                            <h2 class="card-title">Card Three</h2>
                            <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Rem magni quas ex numquam, maxime minus quam molestias corporis quod, ea minima accusamus.</p>
                        </div>
                        <div class="card-footer"><a class="btn btn-primary btn-sm" href="#!">More Info</a></div>
                    </div>
                </div>
            </div>
        </div>

MiProyecto/apps/home/templates/home/navbar.html
 <!-- Responsive navbar-->
 <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container px-5">
        <a class="navbar-brand" href="{% url 'home:index' %}">Punto de Encuentro</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'home:index' %}">Inicio</a></li>
                <li class="nav-item"><a class="nav-link" href="#!">Nuestra Historia</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'producto:index'  %}">Productos</a></li>
                
                <li class="nav-item"><a class="nav-link" href="#!">Contactanos</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'voluntariado:index' %}">Voluntariado</a></li>
            </ul>
        </div>
    </div>
</nav>

MiProyecto/apps/producto/templates/producto/index.html
{% extends 'home/base.html' %}

{% block content %}
    <h1>Productos</h1>

    {% block content_producto %}
        <h3>Categorias de Productos</h3>
        <a href="{% url 'producto:producto_categoria_list' %}">Listar</a> <br>
        <a href="{% url 'producto:producto_categoria_pedido' %}">Encargar producto</a>
    {% endblock content_producto %}
{% endblock content %}

MiProyecto/apps/producto/templates/producto/producto_categoria_delete.html
{% extends 'producto/index.html' %}

{% block content_producto %}

    <h2>Eliminacion de Categoria de Productos</h2>
    <p>¿Confirma eliminar "{{categoria}}"?</p>
<form method="post">
    {% csrf_token %}
    <button type="submit">Confirmar</button>
</form>
    <a href="{% url 'producto:index' %}">Volver a indice de Productos</a>
{% endblock content_producto %}

MiProyecto/apps/producto/templates/producto/producto_categoria_list.html
{% extends 'producto/index.html' %}

{% block content_producto %}

    <h2>Lista  de Categorias de Productos</h2>
    
    {% for categoria in categorias %}
    <ul>
        <li>{{categoria}}
            <a href="{% url 'producto:producto_categoria_update' categoria.id %}"class="btn btn-primary">Actualizar</a>
            <a href="{% url 'producto:producto_categoria_delete' categoria.id %}"class="btn btn-danger">Eliminar</a>
        </li>
    </ul>
    {% endfor %}

    <a href="{% url 'producto:index' %}">Volver a indice de Productos</a>
{% endblock content_producto %}

MiProyecto/apps/producto/templates/producto/producto_categoria_pedido.html
{% extends 'producto/index.html' %}

{% block content_producto %}

    <h3>Crear pedidos de Productos</h3>

        <form method="post">
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit">Encargar</button>
        </form>
    <a href="producto:index">Volver al indice de productos</a>
{% endblock content_producto %}

    

MiProyecto/apps/producto/templates/producto/producto_categoria_update.html
{% extends 'producto/index.html' %}

{% block content_producto %}

    <h3>Actualizar producto</h3>

        <form method="post">
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit">Actualizar</button>
        </form>
    <a href="producto:index">Volver al indice de productos</a>
{% endblock content_producto %}

    

MiProyecto/apps/voluntariado/templates/voluntariado/index.html
{% extends 'home/base.html' %}

{% block content %}
    <h1>Voluntariado</h1>
{% endblock content %}

MiProyecto/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>
        {% block TITULO %}
            Bienvenido a mi proyecto Django
        {% endblock TITULO %}
    </h1>
    {%  block CONTENIDO %}
    {% endblock CONTENIDO %} 
    
</body>
</html>

MiProyecto/templates/index.html
{% extends 'base.html' %}
{% block CONTENIDO %}
    <a href="{% url 'cliente:index' %}">Ir a Clientes</a>
{% endblock CONTENIDO %}
    
    